// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    $(".front").draggable();
    return $(".front").click(function() {
      var request;
      console.log(this);
      request = $.get('/');
      request.success(function(data) {
        return $('body').append("Successfully got the page again.");
      });
      return request.error(function(jqXHR, textStatus, errorThrown) {
        return $('body').append("AJAX Error: ${textStatus}.");
      });
    });
  });

}).call(this);
