// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    return $("#src").keyup(function(e) {
      var length, me, val;
      me = $("#src");
      val = me.val();
      length = val.length;
      $("#len").html(length);
      return $.post('http://127.0.0.1:8081/', {
        src: me.val()
      }, function(data) {
        $("#fp").val(data);
        return $("#sp").val(data);
      });
    });
  });

}).call(this);
